### ISSUE TITLE
Is the paper online published? 

### ISSUE THREAD

**Issue by Cbanyungong** [ShichengMiao16/VRDet#1]
Where is the paper of "Precise Vertex Regression and Feature Decoupling for Oriented Object Detection"? Is is online published?  I didn't find it. Could you share the website of this article?

**Comment by ShichengMiao16** [comment]
The paper has been accepted by the IEEE International Geoscience and Remote Sensing Symposium 2022 recently and it will be published online soon. Thanks for your attention!
